# Generated by Django 6.0 on 2025-12-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='full_name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
