# Generated by Django 6.0 on 2025-12-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraCourse',
            new_name='CourseInfo',
        ),
    ]
