# Generated by Django 6.0 on 2025-12-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_extracourse_courseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(max_length=50)),
                ('related_course', models.CharField(help_text='Related main course (e.g. CS, IT, Business)', max_length=100)),
            ],
        ),
    ]
