# Generated by Django 6.0 on 2025-12-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_extracourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='extra_courses/'),
        ),
        migrations.AlterField(
            model_name='extracourse',
            name='related_course',
            field=models.CharField(max_length=100),
        ),
    ]
