# Generated by Django 6.0 on 2025-12-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_jobposting_delete_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='status',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
