"""
Django settings for aub_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r7%o)&!gp+0-@tlr_%(02umr0@t8cn^-qs*w(6*tk-1l_wr8@g'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = ['aubapp-django.up.railway.app', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['https://aubapp-django.up.railway.app']


# Application definition

INSTALLED_APPS = [
    "jazzmin",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'django_filters',
    'rest_framework.authtoken',

    'api',
]


# ======================
# JAZZMIN CONFIG (AUB STYLE)
# ======================

JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "AUB Admin",
    "site_header": "AUB Admin Panel",
    "site_brand": "AUB",
    "site_logo": "images/whitelogo.png",
    "login_logo": "images/whitelogo.png",
    "login_logo_dark": "images/whitelogo.png",

    # UI
    "welcome_sign": "Welcome to AUB Admin Panel",
    "copyright": "AUB © 2026",

    # Enable theme builder (dark / light switch)
    "show_ui_builder": True,

    # Default theme
    "theme": "darkly",

    # Custom CSS
    "custom_css": "admin/css/custom.css",

    # Top menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # Icons
    "icons": {
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "api.courseinfo": "fas fa-info-circle",
        "api.course": "fas fa-graduation-cap",
        "api.jobposting": "fas fa-briefcase",
        "api.book": "fas fa-book",

        "api.enrollment": "fas fa-user-check",
        "api.eventmenu": "fas fa-utensils",
        "api.extracourse": "fas fa-plus-circle",
        "api.news": "fas fa-newspaper",

        "authtoken.TokenProxy": "fas fa-key",

    },
}


JAZZMIN_UI_TWEAKS = {
    # Dark / Light mode
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "light_mode_theme": "flatly",

    # Layout
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-primary",

    # Buttons
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },

    # Sidebar tweaks
    "sidebar_fixed": True,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_compact_style": False,
}


# ======================
# MIDDLEWARE
# ======================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

# ======================
# URLS & TEMPLATES
# ======================

ROOT_URLCONF = 'aub_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aub_backend.wsgi.application'


# ======================
# DATABASE
# ======================

# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import os
from dotenv import load_dotenv

load_dotenv()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# ======================
# AUTH / PASSWORDS
# ======================

# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ======================
# INTERNATIONALIZATION
# ======================

# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ======================
# CORS
# ======================

CORS_ALLOW_ALL_ORIGINS = True


# ======================
# STATIC & MEDIA
# ======================

# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # For production static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' # For production static files
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ======================
# DJANGO REST FRAMEWORK
# ======================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# ======================
# DEFAULT PRIMARY KEY
# ======================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

